source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# Uncomment to use a git copy
PLAYKIT_GIT='https://github.com/kaltura/playkit-ios.git'
PLAYKIT_IMA_GIT='https://github.com/kaltura/playkit-ios-ima.git'

PLAYKIT_BRANCH=ENV['PK_BRANCH'] || 'develop'
PLAYKIT_IMA_BRANCH=ENV['PK_IMA_BRANCH'] || 'develop'


abstract_target 'SharedPods' do
  if defined? PLAYKIT_LOCAL
    pod 'PlayKit', :path => PLAYKIT_LOCAL
    else
    if defined? PLAYKIT_GIT
      pod 'PlayKit', :git => PLAYKIT_GIT, :branch => PLAYKIT_BRANCH
      else
      pod 'PlayKit'
    end
  end
  
  if defined? PLAYKIT_IMA_LOCAL
    pod 'PlayKit_IMA', :path => PLAYKIT_IMA_LOCAL
    else
    if defined? PLAYKIT_IMA_GIT
      pod 'PlayKit_IMA', :git => PLAYKIT_IMA_GIT, :branch => PLAYKIT_IMA_BRANCH
      else
      pod 'PlayKit_IMA'
    end
  end
  target 'VideoSample'
end


#target 'VideoSample' do
#  use_frameworks!

#  pod 'PlayKit'
#  pod 'PlayKit_IMA'
  
  target 'VideoSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

#end
